import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { AnimatePresence } from "framer-motion";
import localFont from "next/font/local";
import { Providers } from "@/components/providers";

const zenAntiqueSoft = localFont({
  src: [
    {
      path: "../fonts/ZenAntiqueSoft-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-zen-antique-soft",
  display: "swap",
});

const tildaSans = localFont({
  src: [
    {
      path: "../fonts/TildaSans-Regular.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-tilda-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${zenAntiqueSoft.variable} ${tildaSans.variable}`}>
      <body className="antialiased">
        <Providers>
          <Header />
          <AnimatePresence mode="wait">
            <main className="bg-[var(--color-background)]">{children}</main>
          </AnimatePresence>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
